repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: isort .
        language: python
        types: [ python ]
        pass_filenames: false

      - id: black
        name: black
        entry: black .
        language: python
        types: [ python ]
        pass_filenames: false

      - id: flake8
        name: flake8
        entry: flake8 .
        language: python
        types: [ python ]
        pass_filenames: false
